add cm

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -1,5 +1,4 @@
-name: Build and Test
-
+name: build-and-test
 on:
   workflow_call:
 
@@ -20,3 +19,12 @@ jobs:
           cd ./jam-api/cmd/api
           go build -v ./...
           go test -v ./...
+          if [ $? -eq 0 ]; then
+            echo "::set-output name=status::success"
+          else
+            echo "::set-output name=status::failure"
+            exit 1
+          fi
+      # - name: Output Status
+      #   run: |
+      #     echo "Status: ${{steps.build-and-test.outputs.status}}"
