create pre push

diff --git a/.github/workflows/pre-push.yml b/.github/workflows/pre-push.yml
--- a/.github/workflows/pre-push.yml
+++ b/.github/workflows/pre-push.yml
@@ -1,6 +1,10 @@
-name: Go package
+name: Pre-push
 
-on: [push]
+on:
+  push:
+    branches:
+      - main
+      - dev
 
 jobs:
   build-and-test:
@@ -20,3 +24,11 @@ jobs:
           cd ./jam-api/cmd/api
           go build -v ./...
           go test -v ./...
+      
+      - name: Check if tests passed
+        run: |
+          if [ $? -ne 0 ]
+          then
+            echo "Tests failed. Push denied."
+            exit 1
+          fi
